name: OpenEmbedded Build

# Controls when the workflow is triggered.
# This example is set to manually trigger, which is useful for long-running builds.
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    # Runs on the latest Ubuntu runner hosted by GitHub.
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute OpenEmbedded build commands
        run: |
          echo "Starting the OpenEmbedded build process..."
          
          # Install necessary dependencies
          echo "Installing system dependencies..."
          sudo apt-get update
          sudo apt-get install -y autoconf automake bison bzip2 chrpath cmake coreutils cpio curl cvs debianutils default-jre default-jre-headless diffstat flex \
                                  g++ gawk gcc gcc-12 gcc-multilib g++-multilib gettext git gzip help2man info iputils-ping java-common libc6-dev libc6-dev-i386 \
                                  libglib2.0-dev libncurses-dev libperl4-corelibs-perl libproc-processtable-perl libsdl1.2-dev libserf-dev libtool libxml2-utils \
                                  make ncurses-bin patch perl pkg-config psmisc python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-setuptools \
                                  quilt socat sshpass subversion tar texi2html texinfo unzip wget xsltproc xterm xz-utils zip zlib1g-dev zstd fakeroot lz4 git-lfs

          # Create a symbolic link for /bin/sh
          echo "Setting up /bin/sh link..."
          sudo ln -sf /bin/bash /bin/sh

          # Set kernel parameters to increase inotify watches
          echo "Adjusting kernel parameters for inotify..."
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -n -w fs.inotify.max_user_watches=524288
          echo 'kernel.apparmor_restrict_unprivileged_userns=0' | sudo tee /etc/sysctl.d/60-apparmor-namespace.conf > /dev/null && sudo sysctl --system
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          
          # Configure Git user details
          echo "Configuring Git user..."
          git config --global user.email "ahmedmoselhi55@gmail.com"
          git config --global user.name "ahmedmoselhi"

          # Clone the build environment and initialize
          echo "Cloning and initializing build environment..."
          git clone https://github.com/oe-alliance/build-enviroment.git -b 5.6 && cd build-enviroment
          make update
          
          # Set up the machine-specific build environment
          echo "Initializing the build for novaler4kpro..."
          MACHINE=novaler4kpro DISTRO=opendroid DISTRO_TYPE=release make init
          
          # Navigate into the build directory
          echo "Entering the build directory..."
          cd builds/opendroid/release/multiboxpro/

          # Source the environment variables and start the BitBake build
          echo "Starting the BitBake process..."
          source env.source
          bitbake opdmultiboot

